---
title: \href{https://fgeerolf.github.io/teaching/ECON221/lecture3.pdf}{Lecture 3 - Consumption}
subtitle: \href{https://fgeerolf.github.io/teaching/ECON221/}{UCLA - Econ 221 - Fall 2018}
author: \href{https://fgeerolf.github.io/}{François Geerolf}
header-includes:
- \usepackage{fancyhdr}
- \usepackage{lipsum}
- \pagestyle{fancy}
- \fancyhf{}
- \fancyfoot[C]{\thepage}
- \fancyhead[L]{\href{https://fgeerolf.github.io/teaching/ECON221/}{UCLA - Econ 221 - Fall 2018 - Geerolf}}
- \fancyhead[R]{\href{https://fgeerolf.github.io/teaching/ECON221/lecture3.pdf}{Consumption}}
output:
  pdf_document:
    number_sections: true
    citation_package: natbib
    fig_caption: yes
    toc: yes
  html_document: default
bibliography: 221.bib
---


# Theory

Assume that:
$$U\left(c_{1},c_{2}\right)=u\left(c_{1}\right)+\beta u\left(c_{2}\right)$$

Income is $y_{1}$ and consumption is $c_{1}$, so that:
$$a=y_{1}-c_{1}$$

Income is $y_{2}$ and consumption is $c_{2}$, so that:c_{2}=y_{2}+(1+r)a

Budget constraint:
$$c_{1}+\frac{1}{1+r}c_{2}=y_{1}+\frac{1}{1+r}y_{2}$$

TRherefore, the household problem is:
$$
\begin{aligned}
&\max_{c_1, c_2} \quad u\left(c_{1}\right)+\beta u\left(c_{2}\right)\\
&\quad \text{s.t.}\quad c_{1}+\frac{1}{1+r}c_{2}	=y_{1}+\frac{1}{1+r}y_{2}
\end{aligned}
$$

Forming the Lagrangian:
$$L\left(c_{1},c_{2},\lambda\right)=u\left(c_{1}\right)+\beta u\left(c_{2}\right)-\lambda\left[c_{1}+\frac{1}{1+r}c_{2}-y_{1}-\frac{1}{1+r}y_{2}\right]$$

Therefore:
$$
\begin{aligned}
u^{\prime}\left(c_{1}\right)-\lambda	&=0\\
\beta u^{\prime}\left(c_{2}\right)-\lambda\frac{1}{1+r}	&=0
\end{aligned}
$$

Finally:
$$u^{\prime}\left(c_{1}\right)=\beta(1+r)u^{\prime}\left(c_{2}\right)$$

**CRRA utility.** Using the CRRA utility:
$$u(c)=\frac{c^{1-\sigma}}{1-\sigma}$$

Marginal utility is:
$$u^{\prime}(c)=c^{-\sigma}$$

Therefore:
$$c_{1}^{-\sigma}=\beta(1+r)c_{2}^{-\sigma}\quad\Rightarrow\quad c_{2}=[\beta(1+r)]^{\frac{1}{\sigma}}c_{1}$$

Replacing in the budget constraint:
$$c_{1}+\frac{1}{1+r}[\beta(1+r)]^{\frac{1}{\sigma}}c_{1}=y_{1}+\frac{1}{1+r}y_{2}$$

Therefore:
$$c_{1}=\frac{y_{1}+\frac{1}{1+r}y_{2}}{1+\beta^{\frac{1}{\sigma}}(1+r)^{\frac{1}{\sigma}-1}}$$


# Data

## @keynes_general_1936, @friedman_theory_1957

## @poterba_finite_1987

## @campbell_why_1989

## @cole_social_1992

@cole_social_1992:

But think for a moment about an already very rich agent such as Donald Trump. Why does he continue to work long days, endure substantial amounts of stress, and take enormous risks? Surely it cannot be that he is savoring the prospect of going to the grocery store with a looser budget constraint next year. He seems to have more money than he could spend in several lifetimes. Even if we are wrong about Trump's net worth, there clearly seem to be wealthy individuals that continue to work very hard and take large risks to increase their net worth. It is hard to reconcile such behavior with the underlying decision making in traditional growth models.We propose that people like Trump continue to care about increasing their net worth because their utility depends not only on the absolute level of their wealth but also on their wealth relative to that of other very rich people.

## @deaton_understanding_1992

If consumers are aware of these facts, as now they should be, and if their current consumption depends on their total lifetime resources, then the younger generations will be saving now to pay the tax bills and the reduced social security that they are going to receive in the future. In the light of the evidence against low-frequency smoothing, and of the limited relevance of expected future income, especially distant future income, it seems unlikely that they will do so. For exactly the same reasons, Ricardian equivalence will not hold, and government deficits will decrease national saving. The US government may not be able to manipulate its fiscal stance in the short run, but its long-term policies are not so constrained, and their consequences are unlikely to be offset by the clear-sighted and far-sighted actions of permanent income consumers.

## @parker_reaction_1999

## @parker_spendthrift_2000

## @carroll_why_2000

## @souleles_consumer_2002

## @johnson_household_2006

## @kaplan_wealthy_2014

## @jappelli_fiscal_2014

In particular, we find that a debt-financed increase in transfers of 1 percent of national disposable income targeted to the bottom decile of the cash-on-hand distribution would increase aggregate consumption by 0.82 percent. Furthermore, redistributing income from the top decile to the bottom decile of the income distribution would boost aggregate consumption by about 0.1 percent. One important caveat is that our calculations of the aggregate effects of fiscal policy are performed assuming no general equilibrium effects, and, in particular, that fiscal policy does not impact asset prices and that tax changes have no effect on labor supply. Hence, our calculations are likely to be an upper bound to the true effects of fiscal policy.

## @saez_wealth_2016

## @parker_why_2017

## @wong_population_2016

In this paper, @souleles_consumer_2002 shows that the consumer response to the Reagan tax cuts was very far from the one which is predicted by the Permanent Income Hypothesis. 