---
title: \href{https://fgeerolf.github.io/teaching/ECON221/papers-to-replicate.pdf}{Papers to Replicate}
subtitle: \href{https://fgeerolf.github.io/teaching/ECON221/}{UCLA - Econ 221 - Fall 2018}
author: \href{https://fgeerolf.github.io/}{François Geerolf}
header-includes:
- \usepackage{fancyhdr}
- \usepackage{lipsum}
- \pagestyle{fancy}
- \fancyhf{}
- \fancyfoot[C]{\thepage}
- \fancyhead[L]{\href{https://fgeerolf.github.io/teaching/ECON221/index.html}{UCLA - Econ 221 - Fall 2018 - Geerolf}}
- \fancyhead[R]{\href{https://fgeerolf.github.io/teaching/ECON221/papers-to-replicate.pdf}{Papers to Replicate}}
output:
  pdf_document:
    citation_package: natbib
    fig_caption: yes
    toc: no
  html_document: default
---

# Three options

[This article called "Publication, Publication"](https://www.cambridge.org/core/journals/ps-political-science-and-politics/article/publication-publication/70648B31FD6FB98426AF06624A4B0FB4) has convinced me that a great way to write a publishable paper is to start with the replication of a published article. This replication exercise will count towards 80% of your final grade. You may either work alone, in which case you need to replicate one paper, or work in pairs, in which case you need to replicate two. For choosing papers, you have three options:

1. One is to choose one paper in the [below indicative list](#list) of papers to replicate; I have a weak preference for this option.

2. If you are not interested to replicate any of these papers (for instance, because this is not the type of research that you would like to be writing), you may choose any alternative paper from the non successfully replicated paper in this list - they have either missing data or code:
[Andrew C. Chang and Phillip Li. "Is Economics Research Replicable? Sixty Published Papers From Thirteen Journals Say “Often Not”", Forthcoming at _Critical Finance Review_](https://www.nowpublishers.com/article/Download/CFR-0053).
The list of papers is [in the online appendix of that paper](https://sites.google.com/site/andrewchristopherchang/ChangandLi_GDPReplicationPaper_CFR_PreprintVersion_Appendix.pdf?attredirects=0&d=1) - again, you should choose one of the paper for which the data is public, but which failed to replicate for reasons of missing data, or code, or both.

3. You may replicate any other empirical macro-finance paper. However, in this case, the code and data should not be available from the authors' website - or at least, the results should not replicate using only what the authors have provided. The idea is for you to engage in some replication of the results. You should send me the paper you would like to replicate for approval. In particular, I will not allow papers which are too "financy", "marginal" or "inside baseball", in the sense that it should have implications for macroeconomics as well. The paper should be as general interest or policy relevant as possible. For a finance paper, there should be some implications for investment behavior - it should be Macro-Finance, not pure asset pricing.

# Indicative List {#list}

Note that some of these papers do not always have regressions in them - some are just "facts" papers. However, this papers are sometimes very interesting. Descriptive statistics are sometimes useful, and it's also useful to investigate how robust they are.

1. [Blanchard, Olivier Jean, Lawrence F. Katz, Robert E. Hall, and Barry Eichengreen. “Regional Evolutions.” Brookings Papers on Economic Activity 1992, no. 1 (1992): 1–75.](https://doi.org/10.2307/2534556)  
**Anthony Papac**   

2. [Eichenbaum, Martin, Benjamin K. Johannsen, and Sergio Rebelo. “Monetary Policy and the Predictability of Nominal Exchange Rates.” Working Paper. National Bureau of Economic Research, February 2017.](https://doi.org/10.3386/w23158)  
**Alvaro Boitier**

3. Debate between Lauren Cohen, Joshua Coval & Christopher Malloy, and Jason Alan Snyder & Ivo Welch:  
[Cohen, Lauren, Joshua Coval, and Christopher Malloy. “Do Powerful Politicians Cause Corporate Downsizing?” Journal of Political Economy 119, no. 6 (December 1, 2011): 1015–60.](https://doi.org/10.1086/664820)  
[Snyder, Jason Alan, and Ivo Welch. “Do Powerful Politicians Really Cause Corporate Downsizing?” Journal of Political Economy 125, no. 6 (July 31, 2017): 2225–31.](https://doi.org/10.1086/694204)  
[Cohen, Lauren, Joshua Coval, and Christopher Malloy. “Reply: Do Powerful Politicians Really Cause Corporate Downsizing?” Journal of Political Economy 125, no. 6 (July 31, 2017): 2232–37.](https://doi.org/10.1086/694203)  
**Sumit Shinde**  

4. [Lewis Alexander and Janice Eberly, “Investment Hollowing Out,” IMF Economic Review 66, no. 1 (March 1, 2018): 5–30.](https://www.imf.org/external/np/res/seminars/2016/arc/pdf/Alexander_Eberly_Session2.pdf)  
**Denis Mokanov**

5. [Germán Gutiérrez and Thomas Philippon, “Investment-Less Growth: An Empirical Investigation,” Working Paper (National Bureau of Economic Research, December 2016).](https://www.brookings.edu/wp-content/uploads/2018/02/gutierreztextfa17bpea.pdf)  
**Salil Gadgil**  

6. [Jan De Loecker and Jan Eeckhout, "The Rise of Market Power and the Macroeconomic Implications", August 24, 2017.](http://www.janeeckhout.com/wp-content/uploads/RMP.pdf)

7. [A. J. Auerbach and Y. Gorodnichenko, “Measuring the Output Responses to Fiscal Policy,” American Economic Journal: Economic Policy, vol. 4, no. 2, pp. 1–27, 2012](https://www.aeaweb.org/articles?id=10.1257/pol.4.2.1)

8. [Stefano DellaVigna and Matthew Gentzkow, “Uniform Pricing in US Retail Chains,” Working Paper (National Bureau of Economic Research, November 2017).](https://www.nber.org/papers/w23996)

9. [Mountford, A. and H. Uhlig. 2009. “What Are the Effects of Fiscal Policy Shocks?” Journal of Applied Econometrics. 24(6): 960–992.](http://www.jstor.org/stable/25608774)  
**Paul Hübner & Paul Momtaz**

10. [Harald Uhlig, “What Are the Effects of Monetary Policy on Output? Results from an Agnostic Identification Procedure,” Journal of Monetary Economics 52, no. 2 (March 1, 2005): 381–419.](https://doi.org/10.1016/j.jmoneco.2004.05.007)  
**Magnus Irie**

11. [Mertens, K. and M. O. Ravn. 2012. “Empirical Evidence on the Aggregate Effects of Anticipated and Unanticipated US Tax Policy Shocks”. American Economic Journal: Economic Policy. 4(2): 145–181](https://doi.org/10.1257/pol.4.2.145)  

12. [Roberto Perotti, “The Effects of Tax Shocks on Output: Not So Large, but Not Small Either,” American Economic Journal: Economic Policy 4, no. 2 (May 2012): 214–37.](https://doi.org/10.1257/pol.4.2.214)  
**James O'Neill**

13. [Kerwin Kofi Charles, Erik Hurst, Mariel Schwartz, "The Transformation of Manufacturing and the Decline in U.S. Employment", March 12, 2018.](https://www.nber.org/chapters/c14081.pdf)  
**Shihan Shen**  

# Other Choices 

1. [Mitchell A. Petersen, “Estimating Standard Errors in Finance Panel Data Sets: Comparing Approaches,” The Review of Financial Studies 22, no. 1 (January 1, 2009): 435–80.](https://doi.org/10.1093/rfs/hhn053)  
**Paul Hübner & Paul Momtaz**

2. [Nicola Cetorelli and Linda S. Goldberg, “Banking Globalization and Monetary Transmission,” The Journal of Finance 67, no. 5 (October 1, 2012): 1811–43.](https://doi.org/10.1111/j.1540-6261.2012.01773.x)  
**Edward Kim**