---
title: \href{https://fgeerolf.github.io/teaching/ECON221/R-cheatsheet.pdf}{R Cheatsheet}
subtitle: \href{https://fgeerolf.github.io/teaching/ECON221/}{UCLA - Econ 221 - Fall 2018}
author: \href{https://fgeerolf.github.io/}{François Geerolf}
header-includes:
- \usepackage{fancyhdr}
- \usepackage{lipsum}
- \pagestyle{fancy}
- \fancyhf{}
- \fancyfoot[C]{\thepage}
- \fancyhead[L]{\href{https://fgeerolf.github.io/teaching/ECON221/}{UCLA - Econ 221 - Fall 2018 - Geerolf}}
- \fancyhead[R]{\href{https://fgeerolf.github.io/teaching/ECON221/R-cheatsheet.pdf}{R Cheatsheet}}
output:
  html_document: default
  pdf_document:
    citation_package: natbib
    fig_caption: yes
    toc: no
---

```{r, message = FALSE, echo = FALSE, warning = FALSE}
rm(list = ls())
devtools::install_github("dbnomics/rdbnomics")
pklist <- c("tidyverse", "rdbnomics", "scales", "fredr")
source("https://fgeerolf.github.io/code/load-packages.R")
options(tibble.print_max = 100)
```

# Introduction {-}

This document provides a list of the commands I find myself using the most.

# Graphing

## Scales

To add tickers with percentage:

```{r, eval = FALSE}
scale_y_continuous(breaks = 0.01*seq(-1, 3.5, 0.25),
                   labels = scales::percent_format(accuracy = 0.05))
```

```{r, fig.height = 3, fig.width = 6, echo = FALSE, fig.align = "center", warning = FALSE}
fredr(series_id = "FYOIGDA188S") %>%
  mutate(year = date %>% substr(1, 4) %>% as.numeric,
         value = value / 100) %>%
  ggplot(data = ., mapping = aes(x = year, y = value)) +
  geom_line() +
  labs(x = "Observation Date", y = "Rate") +
  theme_bw() +
  theme(legend.title = element_blank(),
        legend.position = c(0.4, 0.8)) +
  scale_x_continuous(breaks = seq(1920, 2025, 5)) + 
  scale_y_continuous(breaks = 0.01*seq(-1, 3.5, 0.25),
                     labels = scales::percent_format(accuracy = 0.05)) + 
  xlab("") + ylab("Interest Payments (% of GDP)")
```
