---
title: \href{https://fgeerolf.github.io/teaching/ECON221/lecture1.pdf}{Lecture 1 - Thoughts on Empirical Macro and Finance}
subtitle: \href{https://fgeerolf.github.io/teaching/ECON221/}{UCLA - Econ 221 - Fall 2018}
author: \href{https://fgeerolf.github.io/}{François Geerolf}
header-includes:
- \usepackage{fancyhdr}
- \usepackage{lipsum}
- \pagestyle{fancy}
- \fancyhf{}
- \fancyfoot[C]{\thepage}
- \fancyhead[L]{\href{https://fgeerolf.github.io/teaching/ECON221/}{UCLA - Econ 221 - Fall 2018 - Geerolf}}
- \fancyhead[R]{\href{https://fgeerolf.github.io/teaching/ECON221/lecture1.pdf}{Empirical Macro and Finance}}
output:
  pdf_document:
    number_sections: true
    citation_package: natbib
    fig_caption: yes
    toc: yes
  html_document: default
bibliography: 221.bib
---

# General comments about research

## Macro or micro ?

Axel Leijonhufvud, professor emeritus at UCLA, says it best in "Life among the Econ" (@leijonhufvud_life_1973):

> Whatever may have been the case in earlier times. the “fields” of the Econ apparently do not now form a strong rank-ordering. This may be the clue to the problem of the non-transitivity of individual status. First, the ordering of two castes will sometimes be indeterminate. Thus, while the Micro assert their superiority over the Macro, so do the Macro theirs over the Micro, and third parties are found to have no very determined, or at least no unanimous, opinion on the matter. Thus the perceived prestige of one caste relative to another isa non-reflexive relation. In other instances, however, the ranking is quite clear. The priestly caste (the Math-Econ) for example, is a higher "field" than either Micro or Macro, while the Devlops just as definitely rank lower. Second, we know that these caste-rankings (where they can be made) are not permanent but may change over time. There is evidence, for example, that both the high rank assigned to the Math-Econ and the low rank of the Devlops are, historically speaking, rather recent phenomena. The rise of the Math-Econ seems to be associated with the previously noted trend among all the Econ towards more ornate, ceremonial modls, while the low rank of the Devlops is due to the fact that this caste, in recent times, has not strictly enforced the taboos against association with the Polscis, Sociogs, and other tribes. Other Econ look upon this with considerable apprehension as endangering the moral fiber of the tribe and suspect the Devlops even of relinquishing modl-making.


## Don't take critical comments too seriously

This is true especially if those comments come from me. You are the best judge of your own research; and only you are in a position to judge whether the critique you receive is justified or not. The best published papers have first been met with skepticism by the economics profession, especially those which would eventually form the basis for a Nobel Prize. For example, Rogoff (2001) recounts about his critique of exchange rate models @meese_empirical_1983, which has been a very cited paper, that:

> For a long time, no one did believe us. The editor of the American Economic Review (Robert Clower) sent our manuscript back in return mail with a scathing letter saying that the results are obviously garbage and if we wish to remain in the economics profession, we had better develop a more positive attitude... One then young and now preeminent MIT macroeconomist, when told the findings, forcefully commented (with a French accent) “You just cannot possibly have done it right.”

# My philosophy


First of all, I teach in a coherent way across undergraduates and graduates. 
In contrast, undergraduate eduaction has continued to teach the IS-LM model, while the RBC model was solely taught in graduate schools.

The idea to test macroeconomics, and discipline the model with microeconomic data, goes back to Larry Summers' contributions. 

Larry Summers' contributions: @poterba_honor_1995

# A brief (partial and subjective) history of macroeconomics

Macroeconomics is born with J.M. Keynes who notes that Marshallian Economics he was brought up into failed to explain the crisis, and policy responses. 

# Crisis of Keynesian Thought

Very defensive attitude of New-Keynesian economics.

Possible solution to the paradox: Keynesian prescriptions were never about sticky prices?


# A brief (partial and subjective) history of macroeconomics

Macroeconomics is born with J.M. Keynes who notes that Marshallian Economics he was brought up into failed to explain the crisis, and policy responses.

# Crisis of Keynesian Thought

Very defensive attitude of New-Keynesian economics.

Possible solution to the paradox: Keynesian prescriptions were never about sticky prices?