---
title: \href{https://fgeerolf.github.io/teaching/ECON221/papers-to-present.pdf}{Papers to Present}
subtitle: \href{https://fgeerolf.github.io/teaching/ECON221/}{UCLA - Econ 221 - Fall 2018}
author: \href{https://fgeerolf.github.io/}{François Geerolf}
header-includes:
- \usepackage{fancyhdr}
- \usepackage{lipsum}
- \pagestyle{fancy}
- \fancyhf{}
- \fancyfoot[C]{\thepage}
- \fancyhead[L]{\href{https://fgeerolf.github.io/teaching/ECON221/index.html}{UCLA - Econ 221 - Fall 2018 - Geerolf}}
- \fancyhead[R]{\href{https://fgeerolf.github.io/teaching/ECON221/papers-to-present.pdf}{Papers to Present}}
output:
  pdf_document:
    citation_package: natbib
    fig_caption: yes
    toc: no
  html_document: default
---

# Papers to Present

Below is a choice of papers to present during one of the two last lectures, on November 27, 2018 and December 4, 2018. The presentation should focus on methodology, and the identification strategy in each paper. Potential concerns about identification, and limits of the studies should also be emphasized. These papers are all very recent, at the working paper, revise and resubmit stage (some of them are now forthcoming). The idea is for you to also get an idea of what is required of a modern macroeconomics & finance paper.

1. [Michael Carlos Best, James Cloyne, Ethan Ilzetski, Henrik Kleven. "Estimating the Elasticity of Intertemporal Substitution Using Mortgage Notches.", October 2018](https://docs.wixstatic.com/ugd/b3763a_0af2dca0bf484e75a340e9468f61936e.pdf)   
**Paul Hübner**  

2. [Atif R. Mian, Amir Sufi, and Emil Verner, “How Does Credit Supply Expansion Affect the Real Economy? The Productive Capacity and Household Demand Channels,” SSRN Scholarly Paper (Rochester, NY: Social Science Research Network, July 31, 2018)](https://papers.ssrn.com/abstract=2971086)  
**Salil Gadgil**

3. [Brian Baugh, Itzhak Ben-David, Hoonsuk Park, Jonathan Parker, “Asymmetric Consumption Response of Households to Positive and Negative Anticipated Cash Flows,” August 2018.](https://www.dropbox.com/s/dl/ropryv1gc7lephn/20180831%20Tax%20Refunds.pdf)

4. [Graham McKee and Emil Verner, “The Consumption Response to Extended Unemployment Benefits in the Great Recession,” SSRN Scholarly Paper (Rochester, NY: Social Science Research Network, July 14, 2015).](https://papers.ssrn.com/abstract=2630790)   
**Magnus Irie**

5. [James Cloyne, Kilian Huber, Ethan Ilzetzki, and Henrik Kleven, "The Effect of House Prices on Household Borrowing: A New Approach", September 2018](https://drive.google.com/file/d/0B3NznAC46AHNVVk5d3ZwRkRmREE/view)  
**Paul Momtaz**

6. [Martin Beraja, Andreas Fuster, Erik Hust, and Joe Vavra, "Regional Heterogeneity and the Refinancing Channel of Monetary Policy", September 2018](http://faculty.chicagobooth.edu/erik.hurst/research/BFHV_paper_june_7_2018%20af.pdf)

7. [Kerwin Kofi Charles, Erik Hurst, Mariel Schwartz, "The Transformation of Manufacturing and the Decline in U.S. Employment", March 12, 2018.](https://www.nber.org/chapters/c14081.pdf)  [Valerie Ramey's Discussion.](https://www.nber.org/chapters/c14083.pdf)  
**Shihan Shen**  

8. [Monetary Policy and the Predictability of Nominal Exchange Rates” by Martin Eichenbaum, Benjamin Johannsen and Sergio Rebelo, February 2018.](https://www.nber.org/papers/w23158). [Adrien Auclert's Discussion.](http://web.stanford.edu/%7Eaauclert/EJR_discussion.pdf)  
**Alvaro Boitier**

9. [Martin Eichenbaum, Sergio Rebelo, and Arlene Wong, "State Dependent Effects of Monetary Policy: the Refinancing Channel", November, 2018.](https://static1.squarespace.com/static/576576adbe659449f97e0d35/t/5be119b088251b14103ba05b/1541478856780/November2018) [Daniel Greenwald's Discussion.](http://www.dlgreenwald.com/uploads/4/5/2/8/45280895/erw_discussion_greenwald.pdf)  
**Gabriel Cuevas**

10. [Chodorow-Reich, Gabriel. “Geographic Cross-Sectional Fiscal Spending Multipliers: What Have We Learned?” Working Paper. National Bureau of Economic Research, July 2017.](https://scholar.harvard.edu/files/chodorow-reich/files/cross_sectional_multipliers.pdf)

11. [Marco Di Maggio, Amir Kermani, Christopher Palmer, "How Quantitative Easing Works: Evidence on the Refinancing Channel", December 2016](http://mitsloan.mit.edu/shared/ods/documents/?DocumentID=2835)  
**Edward Kim**

12. [Peter Ganong, Pascal Noel, "Liquidity vs. Wealth in Household Debt Obligations: Evidence from Housing Policy in the Great Recession", August 2018](https://www.nber.org/papers/w24964)  
**James O'Neill**

13. [Mondragon, John, "Household  Credit  and  Employment in  the  Great  Recession", March 19, 2018](https://www.dropbox.com/s/ftp7rj3aciu6kyo/Mondragon2018.pdf?dl=0)  
**Denis Mokanov**

14. [Suarez Serrato and Wingender (2016) “Estimating Local Fiscal Multipliers.” WP.](http://www.jcsuarez.com/Files/Suarez_Serrato-Wingender-ELFM_Resubmitted_2nd_Round.pdf)  
**Sumit Shinde**

15. [Danny Yagan, “Employment Hysterisis From the Great Recession.”, August 2018.](https://eml.berkeley.edu/~yagan/Hysteresis.pdf)  
**Anthony Papac**
