---
title: \href{https://fgeerolf.github.io/teaching/ECON221/syllabus.pdf}{Syllabus}
subtitle: \href{https://fgeerolf.github.io/teaching/ECON221/}{UCLA - Econ 221 - Fall 2018}
author: \href{https://fgeerolf.github.io/}{François Geerolf}
header-includes:
- \usepackage{fancyhdr}
- \usepackage[utf8]{inputenc}
- \usepackage{lipsum}
- \pagestyle{fancy}
- \fancyhf{}
- \fancyfoot[C]{\thepage}
- \fancyhead[L]{\href{https://fgeerolf.github.io/teaching/ECON221/}{UCLA - Econ 221 - Fall 2018 - Geerolf}}
- \fancyhead[R]{\href{https://fgeerolf.github.io/teaching/ECON221/syllabus.pdf}{Syllabus}}
output:
  pdf_document:
    latex_engine: xelatex
    number_sections: true
    citation_package: natbib
    fig_caption: yes
    toc: no
  html_document: default
bibliography: 221.bib
---

# Main Information {-}

**Lectures.** Tuesdays, 5:05-7:25pm. Bunche Hall 9383.

**Office hours.** Email me for an appointment.

**Website.** https://moodle2.sscnet.ucla.edu/course/view/18F-ECON221A-1.

**Grading.** First, I will ask you to replicate two empirical macro or/and finance papers, using publicly available data (e.g. national accounts, Compustat, CRSP, Nielsen Scanner data, other WRDS material, etc.), but for which the replication code was not made available online by the authors (or not fully). I shall give you a list of papers among which to choose. I believe that the best way to learn empirical methods in macroeconomics and finance is to "get your hands dirty", and practice working with data. The first replication exercise will count towards 40% of your final grade, and the second will count towards 40%. Second, I will ask you to present a recent paper in empirical macroeconomics during the last two lectures. (30 minutes each) Again, I will give you a list from which to choose. This will count towards 20% of your final grade.

**Miscelleneous advice.** [Here](useful-resources.html)  I provide miscelleneous hopefully useful resources on researching, presenting, writing, coding, etc.

**Course outline.** This course will follow an inductive, or bottom-up, approach. Whenever possible, I will start from the facts, and review different theories in light of these facts. I will particularly emphasize empirical observations that have not been explained by currently discussed theories. My hope is that you will find here some inspiration for a dissertation topic.

**Textbooks.** I will assume that you have basic knowledge of first year macroeconomics and finance, which can be found in many different textbooks. For macroeconomics, I would recommend:

[Romer, David. Advanced Macroeconomics. McGraw-Hill Education, 2011.](https://www.mheducation.com/highered/product/advanced-macroeconomics-romer/M0073511374.html)

[Galí, Jordi. Monetary Policy, Inflation, and the Business Cycle: An Introduction to the New Keynesian Framework and Its Applications, Second Edition. Princeton University Press, 2015.](https://press.princeton.edu/titles/10495.html)

[Blanchard, Olivier Jean, and Stanley Fischer. Lectures on Macroeconomics. Vol. 12. 3. Cambridge, MA: The MIT Press, 1990.](https://doi.org/10.1016/0164-0704(90)90022-3)

If you are interested in how macroeconomics is used in practice, I strongly recommend:

[Bénassy-Quéré, Agnès, Benoît Coeuré, Pierre Jacquet, and Jean Pisani-Ferry. Economic Policy: Theory and Practice. Vol. 53. 9. Oxford, New York: Oxford University Press, 2013.](https://global.oup.com/academic/product/economic-policy-9780195322736?)

However, there is unfortunately no unified treatment of macroeconomics at the 2nd year Ph.D. Finance. Finance, on the contrary, has two excellent textbooks offering complementary perspectives. John Cochrane's textbook is structured around the stochastic discount factor view of finance; while John Campbell's textbook is more agnostic.

[Cochrane, John H. Asset Pricing (Revised Edition). Princeton University Press, 2009.](https://press.princeton.edu/titles/7836.html)

[Campbell, John Y. Financial Decisions and Markets: A Course in Asset Pricing. Princeton University Press, 2017.](https://press.princeton.edu/titles/11177.html)

**Online Resources.** I strongly recommend the NBER Summer Institute Econometric Lectures. Three of them are related to macroeconomics and finance:

[Summer Institute Econometric Lecture, 2008, “What's New in Econometrics: Time Series”, James H. Stock and Mark W. Watson.](http://www.nber.org/minicourse_2008.html)

[Summer Institute Econometric Lecture, 2010, “Financial Econometrics”, Sydney Ludvigson, Yacine Ait-Sahalia, Michael Brandt, & Andrew Lo.](http://www.nber.org/econometrics_minicourse_2010/)

[Summer Institute Econometric Lecture, 2011, “Computational Tools & Macroeconomic Applications”, Lawrence Christiano and Jesus Fernandez-Villaverde.](http://www.nber.org/econometrics_minicourse_2011/)

John Cochrane has a course on Asset Pricing on Youtube, which I very strongly recommend:

[Cochrane, John H. Asset Pricing, Part 1. YouTube Online Courses.](https://www.youtube.com/playlist?list=PLpccx1MwQZb7t7HJ6lBo4L3DXhknCD0K7)

[Cochrane, John H. Asset Pricing, Part 2. YouTube Online Courses.](https://www.youtube.com/playlist?list=PLpccx1MwQZb6XsKU3O81GrpqaxyyGoHpH)

**Bibliography.** The following contains a list of readings for each lecture. Those with a ☞ sign are papers which will be discussed during class. The first section has some background reading on methodology, empirical macroeconomics and the current state of macroeconomics. (spoiler: it is probably not that good)

# Methodology and the state of macro {-}

[Axel Leijonhufvud, “Life Among the Econ,” Economic Inquiry 11, no. 3 (September 1, 1973): 327–37](https://doi.org/10.1111/j.1465-7295.1973.tb01065.x)

[McCloskey, Donald N. “The Rhetoric of Economics.” Journal of Economic Literature 21, no. 2 (1983): 481–517](http://www.jstor.org/stable/2724987)

[Leamer, Edward E. “Let’s Take the Con Out of Econometrics.” The American Economic Review 73, no. 1 (1983): 31–43.](http://www.jstor.org/stable/1803924)

[Summers, Lawrence H. “Some Skeptical Observations on Real Business Cycle Theory.” Minneapolis Quarterly Review, no. Fall (1986): 23–27.](https://www.minneapolisfed.org/research/qr/qr1043.pdf)

[Summers, Lawrence H. “The Scientific Illusion in Empirical Macroeconomics.” The Scandinavian Journal of Economics 93, no. 2 (1991): 129–48.](https://doi.org/10.2307/3440321)

[Lars Peter Hansen and James J. Heckman, “The Empirical Foundations of Calibration,” Journal of Economic Perspectives 10, no. 1 (March 1996): 87–104.](https://doi.org/10.1257/jep.10.1.87)

[Krugman, Paul. "There is something about macro."](https://web.mit.edu/krugman/www/islm.html)

[Blanchard, Olivier. “The State of Macro.” Annual Review of Economics 1, no. 1 (2009): 209–28.](https://doi.org/10.1146/annurev.economics.050708.142952)

[Angrist, Joshua D., and Jörn-Steffen Pischke. “The Credibility Revolution in Empirical Economics: How Better Research Design Is Taking the Con out of Econometrics.” Journal of Economic Perspectives 24, no. 2 (2010): 3–30.](https://doi.org/10.1257/jep.24.2.3)

[Sims, Christopher A. “But Economics Is Not an Experimental Science.” Journal of Economic Perspectives 24, no. 2 (June 2010): 59–68.](https://doi.org/10.1257/jep.24.2.59)

[Uhlig, Harald. “Economics and Reality.” Journal of Macroeconomics, Has macro progressed?, 34, no. 1 (March 1, 2012): 29–41.](https://doi.org/10.1016/j.jmacro.2010.09.008)

[Romer, Paul M. “The Trouble With Macroeconomics,” 2016.](https://paulromer.net/wp-content/uploads/2016/09/WP-Trouble.pdf)

[Caballero, Ricardo J. “Macroeconomics after the Crisis: Time to Deal with the Pretense-of-Knowledge Syndrome.” The Journal of Economic Perspectives 24, no. 4 (2010): 85–102.](https://www.aeaweb.org/atypon.php?doi=10.1257/jep.24.4.85)

[Stiglitz, Joseph E. “Where Modern Macroeconomics Went Wrong.” Oxford Review of Economic Policy 34, no. 1–2 (January 5, 2018): 70–106.](https://academic.oup.com/oxrep/article/34/1-2/70/4781816)

[Krugman, Paul. “Good Enough for Government Work? Macroeconomics since the Crisis.” Oxford Review of Economic Policy 34, no. 1–2 (January 5, 2018): 156–68.](https://doi.org/10.1093/oxrep/grx052)

# Introduction to Empirical Macro and Finance

## Main readings

☞ [Nakamura, Emi, and Jón Steinsson. “Identification in Macroeconomics.” Journal of Economic Perspectives 32, no. 3 (August 2018): 59–86.](https://doi.org/10.1257/jep.32.3.59)

☞ [Ramey, V. A. “Chapter 2 - Macroeconomic Shocks and Their Propagation.” In Handbook of Macroeconomics, edited by John B. Taylor and Harald Uhlig, 2:71–162. Elsevier, 2016.](https://doi.org/10.1016/bs.hesmac.2016.03.003)

☞ [Blanchard, Olivier, and Roberto Perotti. “An Empirical Characterization of the Dynamic Effects of Changes in Government Spending and Taxes on Output.” The Quarterly Journal of Economics 117, no. 4 (2002): 1329–68.](http://www.jstor.org/stable/4132480)

☞ [Romer, Christina D., and David H. Romer. “Does Monetary Policy Matter? A New Test in the Spirit of Friedman and Schwartz.” NBER Macroeconomics Annual 1989, Volume 4, January 1, 1989, 121–84.](https://doi.org/10.2307/2534527)

☞ [Giavazzi, Francesco, and Marco Pagano. “Can Severe Fiscal Contractions Be Expansionary? Tales of Two Small European Countries.” NBER Macroeconomics Annual 5 (January 1, 1990): 75–111.](https://doi.org/10.1086/654131)

☞ [Romer, Christina D., and David H. Romer. “A New Measure of Monetary Shocks: Derivation and Implications.” American Economic Review 94, no. 4 (September 2004): 1055–84.](https://doi.org/10.1257/0002828042002651)

☞ [Romer, Christina D., and David H. Romer. “The Macroeconomic Effects of Tax Changes: Estimates Based on a New Measure of Fiscal Shocks.” American Economic Review 100, no. 3 (June 2010): 763–801.](https://doi.org/10.1257/aer.100.3.763)


## Additional readings

[Sims, Christopher A. “Macroeconomics and Reality.” Econometrica 48, no. 1 (1980): 1–48.](https://doi.org/10.2307/1912017)

[Cochrane, John H. “Shocks.” Carnegie-Rochester Conference Series on Public Policy 41 (December 1994): 295–364.](https://doi.org/10.1016/0167-2231(94)00024-7)

["Empirical Macroeconomics. Thomas J. Sargent and Christopher A. Sims" Scientific Background on the Sveriges Riksbank Prize in Economic Sciences in Memory of Alfred Nobel 2011.](http://www.sfu.ca/~kkasa/Sargent_Sims_Nobel.pdf)

[Antonio Acconcia, Giancarlo Corsetti, and Saverio Simonelli, “Mafia and Public Spending: Evidence on the Fiscal Multiplier from a Quasi-Experiment,” American Economic Review 104, no. 7 (July 2014): 2185–2209.](https://doi.org/10.1257/aer.104.7.2185)

# Replicating Mian and Sufi

☞ [Saiz, Albert. “The Geographic Determinants of Housing Supply.” The Quarterly Journal of Economics 125, no. 3 (August 1, 2010): 1253–96.](https://doi.org/10.1162/qjec.2010.125.3.1253)

☞ [Mian, Atif, Kamalesh Rao, and Amir Sufi. “Household Balance Sheets, Consumption, and the Economic Slump.” The Quarterly Journal of Economics 128, no. 4 (November 1, 2013): 1687–1726.](https://doi.org/10.1093/qje/qjt020)

☞ [Mian, Atif, and Amir Sufi. “What Explains the 2007–2009 Drop in Employment?” Econometrica 82, no. 6 (November 1, 2014): 2197–2223.](https://doi.org/10.3982/ECTA10451)

# Consumption

## Main readings

☞ [Kotlikoff, Laurence J., and Lawrence H. Summers. “The Role of Intergenerational Transfers in Aggregate Capital Accumulation.” Journal of Political Economy 89, no. 4 (1981): 706–32.](http://www.jstor.org/stable/1833031)

☞ [Poterba, James M., and Lawrence H. Summers. “Finite Lifetimes and the Effects of Budget Deficits on National Saving.” Journal of Monetary Economics 20, no. 2 (September 1, 1987): 369–91.](https://doi.org/10.1016/0304-3932(87)90021-3)

☞ [Summers, Lawrence, Chris Carroll, and Alan S. Blinder. “Why Is U.S. National Saving so Low?” Brookings Papers on Economic Activity 1987, no. 2 (1987): 607–42.](https://doi.org/10.2307/2534491)

☞ [Johnson, David S., Jonathan A. Parker, and Nicholas S. Souleles. “Household Expenditure and the Income Tax Rebates of 2001.” American Economic Review 96, no. 5 (December 2006): 1589–1610.](https://doi.org/10.1257/aer.96.5.1589)

☞ [Carroll, Christopher D. “Why Do the Rich Save So Much?” In Does Atlas Shrug? The Economic Consequences of Taxing the Rich, edited by Joel B. Slemrod, Vol. D. Harvard Univ Pr, 2000.](http://gabriel-zucman.eu/files/teaching/Carroll00.pdf)

☞ [Parker, Jonathan A. “Spendthrift in America? On Two Decades of Decline in the U.S. Saving Rate.” NBER Macroeconomics Annual 1999, January 1, 2000, 317–87.](http://www.nber.org/chapters/c11050)

☞ [Broda, Christian, and Jonathan A. Parker. “The Economic Stimulus Payments of 2008 and the Aggregate Demand for Consumption.” Journal of Monetary Economics, Supplement issue: October 19-20, 2012 Research Conference on “Financial Markets, Financial Policy, and Macroeconomic Activity” Sponsored by the Study Center Gerzensee and the Swiss National Bank, 68 (December 1, 2014): S20–36.](https://doi.org/10.1016/j.jmoneco.2014.09.002)

☞ [Kaplan, Greg, Giovanni Violante, and Justin Weidner. “The Wealthy Hand-to-Mouth.” Brookings Papers on Economic Activity, 2014, 77–138.](http://www.jstor.org/stable/23936272)

☞ [Wong, Arlene. “Population Aging and the Transmission of Monetary Policy to Consumption.” 2016 Meeting Paper. Society for Economic Dynamics, 2016.](https://econpapers.repec.org/paper/redsed016/716.htm)

☞ [Parker, Jonathan A. “Why Don’t Households Smooth Consumption? Evidence from a $25 Million Experiment.” American Economic Journal: Macroeconomics 9, no. 4 (October 2017): 153–83.](https://doi.org/10.1257/mac.20150331)

☞ [Kueng, Lorenz. “Excess Sensitivity of High-Income Consumers.” The Quarterly Journal of Economics 133, no. 4 (November 1, 2018): 1693–1751.](https://doi.org/10.1093/qje/qjy014)

## Additional readings

[Keynes, John Maynard. The General Theory of Employment, Interest, and Money, 1936.](https://cas2.umkc.edu/economics/people/facultypages/kregel/courses/econ645/winter2011/generaltheory.pdf)

[Friedman, Milton. Theory of the Consumption Function. Princeton University Press, 1957.](https://www.nber.org/chapters/c4402.pdf)

[Modigliani, Franco. “Life Cycle, Individual Thrift, and the Wealth of Nations.” The American Economic Review 76, no. 3 (1986): 297–313.](http://www.jstor.org/stable/1813352)

[Campbell, John Y., and N. Gregory Mankiw. “The Response of Consumption to Income: A Cross-Country Investigation.” European Economic Review 35, no. 4 (May 1, 1991): 723–56.](https://doi.org/10.1016/0014-2921(91)90033-F)

[Cochrane, John H. “The Response of Consumption to Income: A Cross-Country Investigation: By J.Y. Campbell and N.G. Mankiw Why Test the Permanent Income Hypothesis?” European Economic Review 35, no. 4 (May 1, 1991): 757–64.](https://doi.org/10.1016/0014-2921(91)90034-G)

[Deaton, Angus. Understanding Consumption. Oxford University Press, 1992.](www.library.fa.ru/files/Deaton-Understanding.pdf)

[Mankiw, N. Gregory. “The Savers-Spenders Theory of Fiscal Policy.” American Economic Review 90, no. 2 (May 2000): 120–25.](https://doi.org/10.1257/aer.90.2.120)

[Blundell, Richard, Luigi Pistaferri, and Ian Preston. “Consumption Inequality and Partial Insurance.” American Economic Review 98, no. 1998 (2008): 1887–1891.](https://doi.org/10.1257/aer.98.5.1887)

# Investment

## Main readings

☞ [Cobb, Charles W., and Paul H. Douglas. “A Theory of Production.” The American Economic Review 18, no. 1 (1928): 139–65.](http://www.jstor.org/stable/1811556)

☞ [Solow, Robert M. “A Contribution to the Theory of Economic Growth.” The Quarterly Journal of Economics 70, no. 1 (1956): 65–94.](https://doi.org/10.2307/1884513)

☞ [Summers, Lawrence H., Barry P. Bosworth, James Tobin, and Philip M. White. “Taxation and Corporate Investment: A Q-Theory Approach.” Brookings Papers on Economic Activity 1981, no. 1 (1981): 67–140.](https://doi.org/10.2307/2534397)

☞ [Hayashi, Fumio. “Tobin’s Marginal Q and Average Q: A Neoclassical Interpretation.” Econometrica 50, no. 1 (1982): 213–24.](https://doi.org/10.2307/1912538)

☞ [Shapiro, Matthew D., Olivier J. Blanchard, and Michael C. Lovell. “Investment, Output, and the Cost of Capital.” Brookings Papers on Economic Activity 1986, no. 1 (1986): 111–64.](https://doi.org/10.2307/2534415)

☞ [Fazzari, Steven M., R. Glenn Hubbard, Bruce C. Petersen, Alan S. Blinder, and James M. Poterba. “Financing Constraints and Corporate Investment.” Brookings Papers on Economic Activity 1988, no. 1 (1988): 141–206.](https://doi.org/10.2307/2534426)

☞ [Cummins, Jason G., Kevin A. Hassett, R. Glenn Hubbard, Robert E. Hall, and Ricardo J. Caballero. “A Reconsideration of Investment Behavior Using Tax Reforms as Natural Experiments.” Brookings Papers on Economic Activity 1994, no. 2 (1994): 1–74.](https://doi.org/10.2307/2534654)

☞ [Piketty, Thomas, and Gabriel Zucman. “Capital Is Back: Wealth-Income Ratios in Rich Countries 1700–2010.” The Quarterly Journal of Economics 129, no. 3 (August 1, 2014): 1255–1310.](https://doi.org/10.1093/qje/qju018)

☞ [Yagan, Danny. “Capital Tax Reform and the Real Economy: The Effects of the 2003 Dividend Tax Cut.” American Economic Review 105, no. 12 (December 2015): 3531–63.](https://doi.org/10.1257/aer.20130098)

## Additional readings

[Solow, Robert M. "Lecture to the memory of Alfred Nobel", December 8, 1987.](https://www.nobelprize.org/prizes/economic-sciences/1987/solow/lecture/)

[Ben Bernanke, Henning Bohn, and Peter C. Reiss, “Alternative Non-Nested Specification Tests of Time-Series Investment Models,” Journal of Econometrics 37, no. 3 (March 1, 1988): 293–326.](https://doi.org/10.1016/0304-4076(88)90008-5)

[Steven N. Kaplan and Luigi Zingales, “Do Investment-Cash Flow Sensitivities Provide Useful Measures of Financing Constraints?,” The Quarterly Journal of Economics 112, no. 1 (February 1, 1997): 169–215.](https://doi.org/10.1162/003355397555163)

[Janice Eberly, Sergio Rebelo, and Nicolas Vincent, “What Explains the Lagged-Investment Effect?,” Journal of Monetary Economics 59, no. 4 (May 1, 2012): 370–80.](https://doi.org/10.1016/j.jmoneco.2012.05.002)

[Lewis Alexander and Janice Eberly, “Investment Hollowing Out,” IMF Economic Review 66, no. 1 (March 1, 2018): 5–30.](https://doi.org/10.1057/s41308-017-0044-2)

# Financial Frictions

## Main readings

☞ [Bernanke, Ben S., and Alan S. Blinder. “The Federal Funds Rate and the Channels of Monetary Transmission.” The American Economic Review 82, no. 4 (1992): 901–21.](http://www.jstor.org/stable/2117350)

☞ [Kashyap, Anil K., Jeremy C. Stein, and David W. Wilcox. “Monetary Policy and Credit Conditions: Evidence from the Composition of External Finance.” The American Economic Review 83, no. 1 (1993): 78–98.](http://www.jstor.org/stable/2117497)

☞ [Kashyap, Anil K., and Jeremy C. Stein. “Monetary Policy and Bank Lending.” In Monetary Policy, edited by N. Gregory Mankiw, 221–261. January. University of Chicago Press, 1994.](http://www.nber.org/chapters/c8334)

☞ [Holmström, Bengt, and Jean Tirole. “Private and Public Supply of Liquidity.” Journal of Political Economy 106, no. 1 (February 1, 1998): 1–40.](https://doi.org/10.1086/250001)

☞ [Kashyap, Anil K, and Jeremy C. Stein. “What Do a Million Observations on Banks Say about the Transmission of Monetary Policy?” The American Economic Review 90, no. 3 (2000): 407–28.](http://www.jstor.org/stable/117336)

☞ [Mitchell, Mark, Lasse Heje Pedersen, and Todd Pulvino. “Slow Moving Capital.” American Economic Review 97, no. 2 (May 2007): 215–20.](https://doi.org/10.1257/aer.97.2.215)

☞ [Krishnamurthy, Arvind, and Annette Vissing-Jorgensen. “The Effects of Quantitative Easing on Interest Rates: Channels and Implications for Policy.” Brookings Papers on Economic Activity, 2011, 215–87.](http://www.jstor.org/stable/41473600)

☞ [Gilchrist, Simon, and Egon Zakrajšek. “Credit Spreads and Business Cycle Fluctuations.” American Economic Review 102, no. 4 (June 2012): 1692–1720.](https://doi.org/10.1257/aer.102.4.1692)

☞ [Jiménez, Gabriel, Steven Ongena, José-Luis Peydró, and Jesús Saurina. “Hazardous Times for Monetary Policy: What Do Twenty-Three Million Bank Loans Say About the Effects of Monetary Policy on Credit Risk-Taking?” Econometrica 82, no. 2 (March 1, 2014): 463–505.](https://doi.org/10.3982/ECTA10104)

☞ [Chodorow-Reich, Gabriel. “The Employment Effects of Credit Market Disruptions: Firm-Level Evidence from the 2008–9 Financial Crisis.” The Quarterly Journal of Economics 129, no. 1 (February 1, 2014): 1–59.](https://doi.org/10.1093/qje/qjt031)

☞ [Gertler, Mark, and Peter Karadi. “Monetary Policy Surprises, Credit Costs, and Economic Activity.” American Economic Journal: Macroeconomics 7, no. 1 (January 2015): 44–76.](https://doi.org/10.1257/mac.20130329)

☞ [Brunnermeier, Markus K., and Yuliy Sannikov. “A Macroeconomic Model with a Financial Sector.” American Economic Review 104, no. 2 (February 2014): 379–421.](https://doi.org/10.1257/aer.104.2.379)

☞ [Giroud, Xavier, and Holger M. Mueller. “Firm Leverage, Consumer Demand, and Employment Losses During the Great Recession.” The Quarterly Journal of Economics 132, no. 1 (February 1, 2017): 271–316.](https://doi.org/10.1093/qje/qjw035)

## Additional readings

[Townsend, Robert M. “Optimal Contracts and Competitive Markets with Costly State Verification.” Journal of Economic Theory 21, no. 2 (October 1, 1979): 265–93.](https://doi.org/10.1016/0022-0531(79)90031-0)

[Bernanke, Ben, and Mark Gertler. “Agency Costs, Net Worth, and Business Fluctuations.” The American Economic Review 79, no. 1 (1989): 14–31.](http://www.jstor.org/stable/1804770) 

[Shleifer, Andrei, and Robert W. Vishny. “The Limits of Arbitrage.” The Journal of Finance 52, no. 1 (March 1, 1997): 35–55.](https://doi.org/10.1111/j.1540-6261.1997.tb03807.x)

[Kiyotaki, Nobuhiro, and John Moore. “Credit Cycles.” Journal of Political Economy 105, no. 2 (April 1, 1997): 211–48.](https://doi.org/10.1086/262072)

[Bernanke, Ben S., Mark Gertler, and Simon Gilchrist. “Chapter 21 The Financial Accelerator in a Quantitative Business Cycle Framework.” In Handbook of Macroeconomics, 1:1341–93. Elsevier, 1999.](https://doi.org/10.1016/S1574-0048(99)10034-X)

[Krishnamurthy, Arvind. “Collateral Constraints and the Amplification Mechanism.” Journal of Economic Theory 111, no. 2 (August 2003): 277–92.](https://doi.org/10.1016/S0022-0531(03)00098-X)

[Campello, Murillo, John R. Graham, and Campbell R. Harvey. “The Real Effects of Financial Constraints: Evidence from a Financial Crisis.” Journal of Financial Economics, The 2007-8 financial crisis: Lessons from corporate finance, 97, no. 3 (September 1, 2010): 470–87.](https://doi.org/10.1016/j.jfineco.2010.02.009)

# Financial Frictions - Asset Pricing

## Main readings

☞ [Brunnermeier, Markus K., and Lasse Heje Pedersen. “Market Liquidity and Funding Liquidity.” The Review of Financial Studies 22, no. 6 (2009): 2201–38.](https://academic.oup.com/rfs/article-abstract/22/6/2201/1592184) 

☞ [He, Zhiguo, and Arvind Krishnamurthy. “Intermediary Asset Pricing.” American Economic Review 103, no. 2 (April 2013): 732–70.](https://doi.org/10.1257/aer.103.2.732)

☞ [Adrian, Tobias, Erkko Etula, and Tyler Muir. “Financial Intermediaries and the Cross-Section of Asset Returns.” The Journal of Finance 69, no. 6 (2014): 2557–2596.](http://onlinelibrary.wiley.com/doi/10.1111/jofi.12189/abstract)

☞ [Muir, Tyler. “Financial Crises and Risk Premia.” The Quarterly Journal of Economics 132, no. 2 (May 1, 2017): 765–809.](https://doi.org/10.1093/qje/qjw045)

☞ [Geerolf, François. “Asset Pricing without Risk Aversion.” Working Paper, 2017, 1–59.](http://www.econ.ucla.edu/fgeerolf/asset-pricing.pdf)

## Additional readings

[Shleifer, Andrei, and Robert W. Vishny. “Liquidation Values and Debt Capacity: A Market Equilibrium Approach.” The Journal of Finance 47, no. 4 (September 1, 1992): 1343–66.](https://doi.org/10.1111/j.1540-6261.1992.tb04661.x)

[Holmström, Bengt, and Jean Tirole. “Financial Intermediation, Loanable Funds, and The Real Sector.” The Quarterly Journal of Economics 112, no. 3 (August 1, 1997): 663–91.](https://doi.org/10.1162/003355397555316)

[Holmström, Bengt, and Jean Tirole. “Private and Public Supply of Liquidity.” Journal of Political Economy 106, no. 1 (February 1, 1998): 1–40.](https://doi.org/10.1086/250001)

[Tirole, Jean. The Theory of Corporate Finance. Princeton University Press, 2006.](https://press.princeton.edu/titles/8123.html)

[Chari, V. V., Patrick J. Kehoe, and Ellen R. McGrattan. “Business Cycle Accounting.” Econometrica 75, no. 3 (May 1, 2007): 781–836.](https://doi.org/10.1111/j.1468-0262.2007.00768.x)

[Hall, Robert E. “The High Sensitivity of Economic Activity to Financial Frictions.” The Economic Journal 121, no. 552 (May 1, 2011): 351–78.](https://doi.org/10.1111/j.1468-0297.2011.02421.x)

[Gertler, Mark, and Nobuhiro Kiyotaki. “Financial Intermediation and Credit Policy in Business Cycle Analysis.” In Handbook of Monetary Economics - Volume 3A, 3:547–599. 11. Elsevier Ltd, 2011.](https://doi.org/10.1016/B978-0-444-53238-1.00011-9)

[Holmström, Bengt, and Jean Tirole. Inside and Outside Liquidity. Cambridge, MA: MIT Press, 2011.](https://www.jstor.org/stable/j.ctt5hhbbv)

[Modigliani, Franco, and Merton H. Miller. “The Cost of Capital, Corporation Finance and the Theory of Investment.” The American Economic Review 48, no. 3 (1958): 261–97.](https://www.jstor.org/stable/1809766)

[Bernanke, Ben S. “Nonmonetary Effects of the Financial Crisis in the Propagation of the Great Depression.” The American Economic Review 73, no. 3 (1983): 257–76.](https://www.jstor.org/stable/1808111)

[He, Zhiguo, Bryan Kelly, and Asaf Manela. “Intermediary Asset Pricing: New Evidence from Many Asset Classes.” Journal of Financial Economics 126, no. 1 (October 1, 2017): 1–35.](https://doi.org/10.1016/j.jfineco.2017.08.002)

# Low interest rate macroeconomics

## Main readings

☞ [Harrod, R. F. “An Essay in Dynamic Theory.” The Economic Journal 49, no. 193 (1939): 14–33.](https://doi.org/10.2307/2225181)

☞ [Domar, Evsey D. “Capital Expansion, Rate of Growth, and Employment.” Econometrica 14, no. 2 (1946): 137–47.](https://doi.org/10.2307/1905364)

☞ Allais, Maurice. “Economie et Intérêt.” Imprimerie Nationale, 1947.

☞ [Malinvaud, Edmond. “Capital Accumulation and Efficient Allocation of Resources.” Econometrica 21, no. 2 (1953): 233–68.](https://doi.org/10.2307/1905538)

☞ [Samuelson, Paul A. “An Exact Consumption-Loan Model of Interest with or without the Social Contrivance of Money.” Journal of Political Economy 66, no. 6 (1958): 467–82.](https://doi.org/10.2307/1826989)

☞ [Diamond, Peter A. “National Debt in a Neoclassical Growth Model.” The American Economic Review 55, no. 5 (1965): 1126–50.](http://www.jstor.org/stable/1809231)

☞ [Tirole, Jean. “Asset Bubbles and Overlapping Generations.” Econometrica 53, no. 5 (1985): 1071–1100.](https://doi.org/10.2307/1911012)

☞ [Abel, Andrew B., N. Gregory Mankiw, Lawrence H. Summers, and Richard J. Zeckhauser. “Assessing Dynamic Efficiency: Theory and Evidence.” The Review of Economic Studies 56, no. 1 (January 1, 1989): 1–19.](https://doi.org/10.2307/2297746)

☞ [Caselli, Francesco, and James Feyrer. “The Marginal Product of Capital.” The Quarterly Journal of Economics 122, no. 2 (May 1, 2007): 535–68.](https://doi.org/10.1162/qjec.122.2.535)

☞ [Geerolf, François. “Reassessing Dynamic Efficiency.” Working Paper, 2013.](https://fgeerolf.github.io/r-g.pdf)

## Additional readings

[Blanchard, Olivier Jean. “Speculative Bubbles, Crashes and Rational Expectations.” Economics Letters 3, no. 4 (January 1, 1979): 387–89.](https://doi.org/10.1016/0165-1765(79)90017-X)

[Sargent, Thomas J., and Neil Wallace. “Some Unpleasant Monetarist Arithmetic.” In Monetarism in the United Kingdom, 15–41. Palgrave Macmillan, London, 1984.](https://doi.org/10.1007/978-1-349-06284-3_2)

[Malinvaud, Edmond. “The Overlapping Generations Model in 1947.” Journal of Economic Literature 25, no. 1 (1987): 103–5.](https://www.jstor.org/stable/2726192)

[Diba, Behzad T., and Herschel I. Grossman. “On the Inception of Rational Bubbles.” The Quarterly Journal of Economics 102, no. 3 (1987): 697–700.](https://doi.org/10.2307/1884225)

[Abel, Andrew. “Can the Government Roll over Its Debt Forever?” Business Review, no. Nov (1992): 3–18.](https://www.philadelphiafed.org/research-and-data/publications/business-review/1992/brnd92aa.pdf)

[Geanakoplos, John. “Overlapping Generations Models of General Equilibrium.” In The New Palgrave Dictionary of Economics Second Edition, edited by Lawrence E. Durlauf, Steven N. and Blume. Palgrave Macmillan, 2008.](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=1138327) 

[Martin, Alberto, and Jaume Ventura. “Theoretical Notes on Bubbles and the Current Crisis.” IMF Economic Review 59, no. 1 (February 2011): 6–40.](https://doi.org/10.1057/imfer.2011.1)

[Farhi, Emmanuel, and Jean Tirole. “Bubbly Liquidity.” The Review of Economic Studies 79, no. 2 (April 1, 2012): 678–706.](https://doi.org/10.1093/restud/rdr039)

[Martin, Alberto, and Jaume Ventura. “Economic Growth with Bubbles.” American Economic Review 102, no. 6 (May 2012): 3033–58.](https://doi.org/10.1257/aer.102.6.3033)

# Heterogeneity: Static / Dynamic

## Main readings

☞ Feenberg, Daniel R., and James M. Poterba. “Income Inequality and the Incomes of Very High-Income Taxpayers: Evidence from Tax Returns.” Tax Policy and the Economy, Volume 7 7, no. January (1993): 145–177.

☞ [Lucas, Robert E. “On the Size Distribution of Business Firms.” The Bell Journal of Economics 9, no. 2 (1978): 508–23.](https://doi.org/10.2307/3003596)

☞ [Rosen, Sherwin. “The Economics of Superstars.” The American Economic Review 71, no. 5 (1981): 845–58.](http://www.jstor.org/stable/1803469)

☞ [Gabaix, Xavier. “Zipf’s Law for Cities: An Explanation.” The Quarterly Journal of Economics 114, no. 3 (1999): 739–67.](https://www.jstor.org/stable/2586883)

☞ [Garicano, Luis. “Hierarchies and the Organization of Knowledge in Production.” Journal of Political Economy 108, no. 5 (October 1, 2000): 874–904.](https://doi.org/10.1086/317671)

☞ [Luttmer, Erzo G. J. “Selection, Growth, and the Size Distribution of Firms.” The Quarterly Journal of Economics 122, no. 3 (2007): 1103–44.](https://www.jstor.org/stable/25098869)

☞ [Gabaix, Xavier. “Power Laws in Economics and Finance.” Annual Review of Economics 1, no. 1 (September 2009): 255–293.](https://doi.org/10.1146/annurev.economics.050708.142940)

☞ [Geerolf, François. “A Theory of Pareto Distributions.” Working Paper, 2016, 1–49.](http://www.econ.ucla.edu/fgeerolf/geerolf-pareto.pdf)

## Additional readings

Pareto, Vilfredo. Cours d’économie politique. Librairie Droz, 1896.

[Champernowne, D. G. “A Model of Income Distribution.” The Economic Journal 63, no. 250 (1953): 318–51.](https://doi.org/10.2307/2227127)

[Hsieh, Chang-Tai, and Peter J. Klenow. “Misallocation and Manufacturing TFP in China and India.” The Quarterly Journal of Economics 124, no. 4 (November 1, 2009): 1403–48.](https://doi.org/10.1162/qjec.2009.124.4.1403)

[Atkinson, Anthony B., Thomas Piketty, and Emmanuel Saez. “Top Incomes in the Long Run of History.” Journal of Economic Literature 49, no. 1 (2011): 3–71.](http://www.jstor.org/stable/29779750)

[Garicano, Luis, and Esteban Rossi-Hansberg. “Organization and Inequality in a Knowledge Economy.” The Quarterly Journal of Economics 121, no. 4 (November 1, 2006): 1383–1435.](https://doi.org/10.1093/qje/121.4.1383)

[Terviö, Marko. “The Difference That CEOs Make: An Assignment Model Approach.” American Economic Review 98, no. 3 (June 2008): 642–68.](https://doi.org/10.1257/aer.98.3.642)

[Gabaix, Xavier, and Augustin Landier. “Why Has CEO Pay Increased So Much?” The Quarterly Journal of Economics 123, no. 1 (February 1, 2008): 49–100.](https://doi.org/10.1162/qjec.2008.123.1.49)

[Benhabib, Jess, Alberto Bisin, and Shenghao Zhu. “The Distribution of Wealth and Fiscal Policy in Economies With Finitely Lived Agents.” Econometrica 79, no. 1 (January 1, 2011): 123–57.](https://doi.org/10.3982/ECTA8416)