---
title: "UCLA, Econ 102 - Fall 2018"
output:
  html_document: default
---

This website contains class material for the class _Econ 102_ at the University of California, Los Angeles (UCLA).  
The class is taught by [François Geerolf](https://fgeerolf.github.io).
The syllabus for the class is available here:

Syllabus. [pdf](syllabus.pdf) / [html](syllabus.html)

All lectures have four versions: 

* one **pdf** version for printing, and one **html** version to view the lecture on your smartphone (if you want to do some Econ 102 on the Big Blue Bus...).
* A **pdf-R** and a **html-R** version for R-geeks, or students who want to learn R Statistical Software. These include the code I use to retrieve live data from official government sources. You may find an introduction to R-statistics here:

Introduction to R (Optional). [pdf](R-intro.pdf) / [html](R-intro.html)

However this is only optional and you do not need to download R, or learn any R command to get an A+ in this class.

## Lectures

Lecture 1. [pdf](lecture1.pdf) / [html](lecture1.html) / [pdf-R](lecture1-R.pdf) / [html-R](lecture1-R.html) / [slides](lecture1-slides.pdf)  
Lecture 2. 
